SELECT
e.EMPLOYEE_ID,
e.FIRST_NAME || ' ' || e.LAST_NAME AS FULL_NAME,
e.SALARY,
d.DEPARTMENT_NAME,
j.JOB_TITLE,
j.MIN_SALARY AS JOB_MIN_SALARY,
j.MAX_SALARY AS JOB_MAX_SALARY
 
FROM HR.EMPLOYEES e
 
LEFT JOIN HR.DEPARTMENTS d
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
 
LEFT JOIN HR.JOBS j
ON e.JOB_ID = j.JOB_ID
 
WHERE e.DEPARTMENT_ID IS NOT NULL
 
ORDER BY
d.DEPARTMENT_NAME ASC,
e.SALARY DESC;
